openapi: 3.0.0
info:
  description: Api documentation for news pipeline
  version: 1.0.0
  title: News Pipeline
servers:
  - url: http://news.f4.htw-berlin.de:8081/api
  - url: http://localhost:8080

tags:
  - name: "articles"
    description: "Retrieve news articles"
  - name: "analytics"
    description: "View analytics for news articles"

paths:
  /articles:
    get:
      tags:
        - "articles"
      summary: "Get news articles"
      description: ""
      operationId: "getArticles"
      parameters:
        - in: query
          name: offset
          schema:
            type: integer
            default: 0
          required: false
          description: Numeric ID of the user to get
        - in: query
          name: count
          schema:
            type: integer
            default: 20
          required: false
          description: Number of articles to return
        - in: query
          name: query
          schema:
            type: string
          required: false
          description: Search query to filter articles
        - in: query
          name: department
          schema:
            type: array
            items:
              type: string
          required: false
          description: Department to filter articles
        - in: query
          name: newspaper
          schema:
            type: array
            items:
              type: string
          required: false
          description: Newspaper to filter articles
        - in: query
          name: author
          schema:
            type: string
          required: false
          description: Author to filter articles
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Article"
        405:
          description: "Invalid input"
  /articles/{articleId}:
    get:
      tags:
        - "articles"
      summary: "Find article by id"
      description: "Only single ID can be provided"
      operationId: "findArticlesByStatus"
      parameters:
        - in: path
          name: "articleId"
          schema:
            type: "integer"
          required: true
          description: "ID of article to return"

      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Article"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Article not found"
  /articles/newspapers:
    get:
      tags:
        - "articles"
      summary: "Get newspapers"
      operationId: "getNewspapers"
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                type: string
        405:
          description: "Invalid input"
  /articles/authors:
    get:
      tags:
        - "articles"
      summary: "Get authors"
      description: "Get authors filtered by query. If no query is given return the top 20 authors"
      operationId: "getAuthors"
      parameters:
        - in: query
          name: query
          schema:
            type: string
          required: false
          description: Query to filter authors
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                type: string
        405:
          description: "Invalid input"
  /analytics/terms:
    get:
      tags:
        - "analytics"
      summary: "Get term occurrences per day"
      operationId: "getTermOccurrences"
      parameters:
        - in: query
          name: query
          schema:
            type: string
          required: true
          description: Term to get occurrences for
        - in: query
          name: timeFrom
          schema:
            type: integer
          required: false
          description: Start date to look for occurrences in milliseconds
        - in: query
          name: timeTo
          schema:
            type: integer
          required: false
          description: End date to look for occurrences in milliseconds
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/TermOccurrences"
        404:
          description: "Term not found in articles"
        405:
          description: "Invalid input"
  /analytics/lemmas:
    get:
      tags:
        - "analytics"
      summary: "Get most relevant lemmas for the last 7 days"
      operationId: "getMostRelevantLemmas"
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Lemma"
        404:
          description: "No articles found for last week"



components:
  schemas:
    Article:
      type: "object"
      properties:
        id:
          type: "string"
        site:
          type: "string"
        title:
          type: "string"
        description:
          type: "string"
        intro:
          type: "string"
        text:
          type: "string"
        url:
          type: "string"

    TermOccurrence:
      type: "object"
      properties:
        date:
          type: "integer"
        dateString:
          type: "string"
        occurrences:
          type: "integer"

    TermOccurrences:
      type: "object"
      properties:
        totalResult:
          type: "integer"
        query:
          type: "string"
        timeFrom:
          type: "integer"
        timeTo:
          type: "integer"
        occurrences:
          type: "array"
          items:
            $ref: "#/components/schemas/TermOccurrence"

    Lemma:
      type: "object"
      properties:
        lemma:
          type: "string"
        docCount:
          type: "integer"


    Filter:
      type: "object"
      properties:
        offset:
          type: "integer"
        count:
          type: "integer"
        query:
          type: "string"
        department:
          type: "string"
        date:
          type: "string"
          format: "date-time"
        newspaper:
          type: "string"
        author:
          type: "string"

    ApiResponse:
      type: "object"
      properties:
        code:
          type: "integer"
          format: "int32"
        type:
          type: "string"
        message:
          type: "string"
